### PR TITLE
Upgrade to CefSharp 47.0.2

### PR DESCRIPTION
**Pull request by amaitland**
Totally understand if you don't wish to merge this, though it might be useful for anyone looking at the article.

> http://www.codeproject.com/Articles/990346/Using-HTML-as-UI-Elements-in-a-WinForms-Applicatio

Fantastic article by the way :+1:

### CODE REVIEW

**Comment by OceanAirdrop** [comment]
Hi Alex,

Thank you. Yes, absolutely. I am happy to accept any improvements to this project. 

I will merge your updates / fixes and then look at updating the article at CodeProject citing your work.

Thanks.

**Comment by amaitland** [comment]
> Thank you. Yes, absolutely. I am happy to accept any improvements to this project.

:smile: 

> I will merge your updates / fixes and then look at updating the article at CodeProject citing your work.

Citation is not necessary, they'll only try track me down and ask more questions! :wink:

**Comment by OceanAirdrop** [comment]
Ha.. So true. ..and so wise. :smile: 

I have already updated the article, but don't worry. I will remove your name as requested.

**Comment by amaitland** [comment]
> I will remove your name as requested.

Don't worry about it, it's perfectly fine :smile:

**Comment by OceanAirdrop** [comment]
No probs. Thanks again. :smile:

**Pull request merged**
